---
title: "Trait EDA"
author: Florian Tanner
date: "`r format(Sys.time())`"
output: html_document
---


```{r}
rm(list=ls())
`%nin%` = Negate(`%in%`)
```

## Load packages

```{r,  message = FALSE}
library(tidyverse)
library(ggplot2); theme_set(theme_bw())
library(patchwork)
```

## Load data

```{r}
hyperspec_2020 <- read_csv("../data/2020/hyperspec_full.csv")
scores_2020 <- read_csv("../data/2020/scores.csv")
```
```{r}
hyperspec_2022 <- read_csv("../data/2022/hyperspec_full.csv")
scores_2022 <- read_csv("../data/2022/scores.csv")
```

## Plot spectrum 2020

```{r}
average_per_treatment_2020 <- hyperspec_2020 |> 
  left_join(scores_2020) |> 
  group_by(wavelength, treatment) |> 
  summarise(mean_treatment_ref = mean(reflectance_smoothed))

average_nil_2020 <- average_per_treatment_2020 |> filter(treatment == "No fungicide")
average_chloro_2020 <- average_per_treatment_2020 |> filter(treatment == "FN Chlorothalonil")
```


```{r}
p_spectrum_2020 <- hyperspec_2020 |> 
  left_join(scores_2020) |> 
  filter(treatment == "No fungicide") |> 
  ggplot(aes(x = wavelength, y = reflectance_smoothed, group = plot_id_fe, color = pad)) +
  geom_line(alpha = 0.7) +
  scale_color_viridis_c() +
  geom_line(data = average_nil_2020, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7, color = "grey80") +
  geom_line(data = average_nil_2020, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7, linetype = 3, color = "black") +
  geom_line(data = average_chloro_2020, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7,  color = "grey80") +
  geom_line(data = average_chloro_2020, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7, linetype = 3,  color = "red") +
  annotate(geom = "label", x = 1450, y = 0.3, label = "Average for \nFN Chlorothalonil\ntreatment", color = "red", size = 3.5) +
  annotate(geom = "label", x = 500, y = 0.13, label = "Average for \nNo Fungicide\ntreatment", color = "black", size = 3.5) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(), 
        legend.position = "bottom", legend.box = "horizontal") +
  labs(x = "Wavelength [nm]", 
       y = "Reflectance", 
       color = "Percent AB damage (No Fungicide treatment only)",
       title = "2020 plots")


p_spectrum_2020
```

```{r}
ggsave(plot= p_spectrum_2020, filename = "out/graphs/spectrum_2020.pdf", device = "pdf", units = "cm", width = 16, height = 12, limitsize = F)
```

## Plot 2022

```{r}
hyperspec_2022 |> 
  filter(!is.na(tray_id),
         is.na(reflectance_raw)) 
```

```{r}
average_per_treatment_2022 <- hyperspec_2022 |> 
  left_join(scores_2022) |> 
  filter(!is.na(tray_id)) |> # 4 trays missing 
  group_by(wavelength, treatment) |> 
  summarise(mean_treatment_ref = mean(reflectance_smoothed))

average_infected_2022 <- average_per_treatment_2022 |> filter(treatment == "Infected")
average_salt_2022 <- average_per_treatment_2022 |> filter(treatment == "Salt + Fungicide")
average_fungicide_2022<- average_per_treatment_2022 |> filter(treatment == "Fungicide")
```

```{r}
p_spectrum_2022 <- hyperspec_2022 |> 
  left_join(scores_2022) |> 
  filter(treatment == "Infected") |>
  ggplot(aes(x = wavelength, y = reflectance_smoothed, group = tray_id, color = pad)) +
  geom_line(alpha = 1) +
  geom_line(data = average_infected_2022, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7, color = "grey80") +
  geom_line(data = average_infected_2022, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7, linetype = 3, color = "black") +
  geom_line(data = average_fungicide_2022, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7,  color = "grey80") +
  geom_line(data = average_fungicide_2022, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7, linetype = 3,  color = "red") +
  geom_line(data = average_salt_2022, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7,  color = "grey80") +
  geom_line(data = average_salt_2022, aes(x = wavelength, y = mean_treatment_ref), 
            inherit.aes = F,  size = 0.7, linetype = 3,  color = "blue") +
  annotate(geom = "label", x = 1550, y = 0.40, label = "Average for \nChlorothalonil\ntreatment", color = "red", size = 3.5) +
  annotate(geom = "label", x = 500, y = 0.23, label = "Average for \nInfection\ntreatment", color = "black", size = 3.5) +
  annotate(geom = "label", x = 1100, y = 0.15, label = "Average for \nSalinity + \nChlorothalonil\ntreatment", color = "blue", size = 3.5) +
  scale_color_viridis_c() +
  scale_y_continuous(limits = c(0, 0.44))+
  labs(x = "Wavelength [nm]", 
       y = "Reflectance", 
       color = "Percent AB damage (No Fungicide / Infected treatment only)",
       title= "2022 trays") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(), 
        legend.position = "bottom", legend.box = "horizontal") 

p_spectrum_2022
```

```{r}
p_spectrum_2020_no_legend <- p_spectrum_2020 + theme(legend.position = "none")
p_spectra <- p_spectrum_2020_no_legend + p_spectrum_2022 + plot_layout(nrow = 2) 
p_spectra
```

```{r}
ggsave(plot= p_spectrum_2022, filename = "out/graphs/spectrum_2022.pdf", device = "pdf", units = "cm", width = 16, height = 12, limitsize = F)
```

```{r}
ggsave(plot= p_spectra, filename = "out/graphs/spectra.pdf", device = "pdf", units = "cm", width = 16, height = 22, limitsize = F)
```


# Correlation in important wavelengths

```{r}
hyperspec_wide_2020 <- hyperspec_2020 |> 
  left_join(scores_2020) |> 
  pivot_wider(id_cols = c(plot_id_fe,treatment), values_from = reflectance_smoothed, names_from = wavelength, names_prefix = "R")

correlations_2020_all_trts <- hyperspec_wide_2020|> 
  filter(treatment %in% c("No fungicide", "FN Chlorothalonil")) |> 
  select(-plot_id_fe, -treatment) |> 
  as.matrix() |> 
  cor() |> 
  as.data.frame() %>%
  mutate(wavelength_x = rownames(.)) |>
  pivot_longer(cols = -wavelength_x, names_to = "wavelength_y") |> 
  mutate(wavelength_x = as.numeric(str_remove(wavelength_x, "R")),
         wavelength_y = as.numeric(str_remove(wavelength_y, "R")))

correlations_2020_infected <- hyperspec_wide_2020 |> 
  filter(treatment =="No fungicide") |> 
  select(-plot_id_fe, -treatment) |> 
  as.matrix() |> 
  cor() |> 
  as.data.frame() %>%
  mutate(wavelength_x = rownames(.)) |>
  pivot_longer(cols = -wavelength_x, names_to = "wavelength_y") |> 
  mutate(wavelength_x = as.numeric(str_remove(wavelength_x, "R")),
         wavelength_y = as.numeric(str_remove(wavelength_y, "R")))
```

```{r}
hyperspec_wide_2022 <- hyperspec_2022 |> 
  left_join(scores_2022) |> 
  filter(!is.na(reflectance_smoothed)) |> 
  pivot_wider(id_cols = c(tray_id, treatment), values_from = reflectance_smoothed, names_from = wavelength, names_prefix = "R", values_fn = mean) 

correlations_2022_all_trts <- hyperspec_wide_2022 |> 
  select(-tray_id, -treatment) |> 
  as.matrix() |> 
  cor() |> 
  as.data.frame() %>%
  mutate(wavelength_x = rownames(.)) |>
  pivot_longer(cols = -wavelength_x, names_to = "wavelength_y") |> 
  mutate(wavelength_x = as.numeric(str_remove(wavelength_x, "R")),
         wavelength_y = as.numeric(str_remove(wavelength_y, "R")))

correlations_2022_infected <- hyperspec_wide_2022 |> 
  filter(treatment == "Infected") |> 
  select(-tray_id, -treatment) |> 
  as.matrix() |> 
  cor() |> 
  as.data.frame() %>%
  mutate(wavelength_x = rownames(.)) |>
  pivot_longer(cols = -wavelength_x, names_to = "wavelength_y") |> 
  mutate(wavelength_x = as.numeric(str_remove(wavelength_x, "R")),
         wavelength_y = as.numeric(str_remove(wavelength_y, "R")))
```
## Plot correlation between bands for all treatments

```{r}
correlations_all_trts <- correlations_2020_all_trts |> 
  mutate(year = 2020) |> 
  bind_rows(correlations_2022_all_trts |> mutate(year = 2022)) 

vnir_width <- (971-410)/207
swir_width <- (1675-971)/100

p_correlations_all_trts <- correlations_all_trts |> 
  mutate(x_min = case_when(wavelength_x < 971 ~ wavelength_x - vnir_width/2,
                           wavelength_x > 971 ~ wavelength_x - swir_width/2),
         x_max = case_when(wavelength_x < 971 ~ wavelength_x + vnir_width/2,
                           wavelength_x > 971 ~ wavelength_x + swir_width/2),
         y_min = case_when(wavelength_y < 971 ~ wavelength_y - vnir_width/2,
                           wavelength_y > 971 ~ wavelength_y - swir_width/2),
         y_max = case_when(wavelength_y < 971 ~ wavelength_y + vnir_width/2,
                           wavelength_y > 971 ~ wavelength_y + swir_width/2)) |> 
  ggplot(aes(x= wavelength_x, y = wavelength_y, color = value*value, 
             xmin = x_min, xmax = x_max, ymin = y_min, ymax = y_max)) +
  geom_rect(alpha = 0.6) +
  # scale_color_viridis_c(limits= c(0,1), ) +
  paletteer::scale_colour_paletteer_c("ggthemes::Blue-Green Sequential", limits= c(0,1)) +
  facet_wrap(~year) +
  labs(x = "Wavelength [nm]", y = "Wavelength [nm]", color = "Squared Pearson's correlation coefficient") +
  theme(legend.position = "bottom")

ggsave(plot = p_correlations_all_trts, filename = "out/graphs/wavelengths_correlations_all_trts.pdf", units = "cm", width = 15, height= 11, limitsize = F)
ggsave(plot = p_correlations_all_trts, filename = "out/graphs/wavelengths_correlations_all_trts.png", units = "cm", width = 15, height= 11, limitsize = F)
```

## Plot correlation between bands for infected

```{r}
correlations_infected <- correlations_2020_infected |> 
  mutate(year = 2020) |> 
  bind_rows(correlations_2022_infected |> mutate(year = 2022)) 

vnir_width <- (971-410)/207
swir_width <- (1675-971)/100

p_correlations_infected <- correlations_infected |> 
  mutate(x_min = case_when(wavelength_x < 971 ~ wavelength_x - vnir_width/2,
                           wavelength_x > 971 ~ wavelength_x - swir_width/2),
         x_max = case_when(wavelength_x < 971 ~ wavelength_x + vnir_width/2,
                           wavelength_x > 971 ~ wavelength_x + swir_width/2),
         y_min = case_when(wavelength_y < 971 ~ wavelength_y - vnir_width/2,
                           wavelength_y > 971 ~ wavelength_y - swir_width/2),
         y_max = case_when(wavelength_y < 971 ~ wavelength_y + vnir_width/2,
                           wavelength_y > 971 ~ wavelength_y + swir_width/2)) |> 
  ggplot(aes(x= wavelength_x, y = wavelength_y, color = value*value, 
             xmin = x_min, xmax = x_max, ymin = y_min, ymax = y_max)) +
  geom_rect(alpha = 0.6) +
  scale_color_viridis_c(limits =c(0,1)) +
  facet_wrap(~year) +
  labs(x = "Wavelength [nm]", y = "Wavelength [nm]", color = "Squared Pearson's correlation coefficient") +
  theme(legend.position = "bottom")

ggsave(plot = p_correlations_infected, filename = "out/graphs/wavelengths_correlations_infected.pdf", units = "cm", width = 15, height= 11, limitsize = F)
ggsave(plot = p_correlations_infected, filename = "out/graphs/wavelengths_correlations_infected.png", units = "cm", width = 15, height= 11, limitsize = F)
```

```{r}
# correlations_2022 |> 
#   filter(value < 0.5) |> 
#   slice_min(order_by = wavelength_y)
```

## Examine correlation between important regions for classification and regression

```{r}
class_important_vars <- read_csv("../classify_treatment/out/metrics/mean_variable_importance_classify_di.csv") |> 
  filter(index %nin% c("Biomass", "Ground cover")) |> 
  mutate(wavelength_num = as.numeric(str_remove(index, "R")))
regress_important_vars <- read_csv("../predict_DI/out/metrics/mean_variable_importance_predict_di.csv")|> 
  filter(index %nin% c("Biomass", "Ground cover")) |> 
  mutate(wavelength_num = as.numeric(str_remove(index, "R"))) |> 
  mutate(spec_region = case_when(wavelength_num < 680 ~ "VIS",
                                 wavelength_num >680 & wavelength_num < 780 ~ "RedEdge",
                                 wavelength_num > 780 & wavelength_num < 1327 ~ "NIR",
                                 wavelength_num > 1327 ~ "SWIR")) 
```

```{r}
class_important_vars <- class_important_vars |> 
  group_by(year) |> 
  slice_max(order_by = rescaled_importance) |> # Get top for each year
  pull(wavelength_num) |> 
  c(756.40) # Add manually chosen

correlations_2020_all_trts |> 
  filter(wavelength_x %in% class_important_vars, 
         wavelength_y %in% class_important_vars)
```
Both years: Corr > 0.99 between all three

```{r}
regress_important_vars_top <- regress_important_vars |> 
  group_by(year, spec_region) |> 
  slice_max(order_by = rescaled_importance) 

regress_important_vars_top

regress_important_vars_vec <- regress_important_vars_top |> 
  filter(spec_region != "SWIR") |> 
  pull(wavelength_num) |> 
  c(792.08) # Manually chosen

regress_important_vars_low_cor <- correlations_2020_infected |> 
  filter(wavelength_x %in% regress_important_vars_vec, 
         wavelength_y %in% regress_important_vars_vec) 

regress_important_vars_low_cor_vec <- regress_important_vars_low_cor |> 
  pull(wavelength_x) |>
  unique()
```


```{r}
sessionInfo()
```
